### PR TITLE
Add wait flag to rollout command

### PR DESCRIPTION
**Pull request by jtrouth**
This should resolve the transient connection issues for SQL proxy and RabbitMQ on deploy

### CODE REVIEW

**Comment by jtrouth** [comment]
Resolves #5 & #6

**Comment by kimberscott** [comment]
Thanks! Trying this out on a build now.

**Comment by kimberscott** [comment]
Ok, I kicked off a fresh lookit-api staging build using a lookit-orchestrator build with this fix at 1:20pm today. Would you be able to look at the logs and let me know if the transient connection errors still happened? I'm having trouble finding the relevant logs in GCP's new logs explorer.

**Comment by jtrouth** [comment]
Still seeing the errors. You can see the errors with the beat pod connecting to sqlproxy with the query `severity=ERROR resource.type="k8s_container" textPayload:"OperationalError"`

I think the solution is going to end up being to add init containers to the pods that wait for the sqlproxy or rabbitmq services to start responding. I'll do some local testing to verify init containers are the solution.

**Pull request merged**
